/**
 * Scoped Plan Generator
 * Synthesizes deep-dive, standalone implementation plans for individual requirements and epics.
 * Captures why each item was planned, its business necessity, acceptance criteria,
 * dependency graph, linked ADRs, and implementation checklist.
 */

import fs from 'fs';
import path from 'path';
import { getTimestamp } from '../utils.js';

export class ScopedPlanGenerator {
  /**
   * Generate an individual implementation plan for a single requirement
   * @param {string} reqId - Requirement ID (e.g. REQ-001)
   * @param {Object} ctx - SkyhookContext
   * @param {Array<Object>} symbols - Scanned codebase symbols
   * @returns {Object} { path, content, req }
   */
  static generateRequirementPlan(reqId, ctx, symbols = []) {
    const skyhookDir = ctx.skyhookDir;
    const funcReqs = ctx.readFunctionalReqs()?.requirements || [];
    const nonFuncReqs = ctx.readNonFunctionalReqs()?.requirements || [];
    const allReqs = [...funcReqs, ...nonFuncReqs];

    const req = allReqs.find(r => r.id === reqId || r.id?.toLowerCase() === reqId?.toLowerCase());
    if (!req) {
      throw new Error(`Requirement not found: ${reqId}`);
    }

    const backlog = ctx.readBacklog();
    const allStories = backlog.stories || [];
    const decisions = ctx.readDecisions()?.decisions || [];

    // Find linked stories
    const linkedStories = allStories.filter(s =>
      (s.relatedRequirements && s.relatedRequirements.includes(req.id)) ||
      s.title?.includes(req.id)
    );

    // Find linked ADRs
    const linkedADRs = decisions.filter(d =>
      (d.relatedRequirements && d.relatedRequirements.includes(req.id)) ||
      d.title?.includes(req.id)
    );

    // Find traced symbols
    const tracedSymbols = symbols.filter(s => s.traced && s.requirementId === req.id);

    // Build directory
    const reqDir = path.join(skyhookDir, 'plan', 'requirements');
    if (!fs.existsSync(reqDir)) {
      fs.mkdirSync(reqDir, { recursive: true });
    }

    const planPath = path.join(reqDir, `${req.id}.md`);

    let content = `# Requirement Plan: ${req.id} — ${req.title || req.userStory || 'Untitled'}\n\n`;
    content += `> **Status**: \`${req.status || 'draft'}\` | **Priority**: \`${req.priority || 'medium'}\` | **Category**: \`${req.category || 'functional'}\`\n`;
    content += `> **Generated**: ${getTimestamp()}\n\n`;
    content += `---\n\n`;

    content += `## 1. Problem Statement & Business Necessity\n\n`;
    content += `${req.description || req.userStory || 'No detailed description provided.'}\n\n`;
    if (req.userStory) {
      content += `> **User Story**:\n> *${req.userStory}*\n\n`;
    }

    content += `## 2. Acceptance Criteria & Definition of Done\n\n`;
    const ac = req.acceptanceCriteria || [];
    if (ac.length > 0) {
      content += ac.map((item, idx) => `- [ ] **AC-${idx + 1}**: ${item}`).join('\n') + '\n\n';
    } else {
      content += `*No formal acceptance criteria registered. Add acceptance criteria to .skyhook/requirements/.*\n\n`;
    }

    content += `## 3. Associated Architectural Decisions (ADRs)\n\n`;
    if (linkedADRs.length > 0) {
      content += linkedADRs.map(d => `- **${d.id}**: ${d.title} (Status: \`${d.status}\`)`).join('\n') + '\n\n';
    } else {
      content += `*No architecture decisions currently reference this requirement.*\n\n`;
    }

    content += `## 4. Backlog Execution & Child Stories\n\n`;
    if (linkedStories.length > 0) {
      content += linkedStories.map(s => {
        const checkbox = s.status === 'done' ? '[x]' : '[ ]';
        return `- ${checkbox} **${s.id}**: ${s.title} [\`${s.status}\`] (Priority: ${s.priority || 'medium'})`;
      }).join('\n') + '\n\n';
    } else {
      content += `*No active backlog stories mapped to this requirement.*\n\n`;
    }

    content += `## 5. Code Implementation & Traced Symbols\n\n`;
    if (tracedSymbols.length > 0) {
      content += `| Symbol | Type | File | Line |\n|:-------|:-----|:-----|:-----|\n`;
      content += tracedSymbols.map(s => `| \`${s.symbolName}\` | \`${s.symbolType}\` | \`${s.file}\` | \`L${s.line}\` |`).join('\n') + '\n\n';
    } else {
      content += `*Pending implementation: No source code symbols currently contain \`@skyhook-implements ${req.id}\`.*\n\n`;
    }

    content += `## 6. Verification & Test Strategy\n\n`;
    content += `1. **Traceability Verification**: Run \`skyhook trace ${req.id}\` to verify all code references.\n`;
    content += `2. **Policy Compliance**: Run \`skyhook adr verify\` to ensure adherence to architectural constraints.\n`;
    content += `3. **Acceptance Verification**: Confirm all AC items above pass automated and regression test suites.\n\n`;
    content += `---\n*Generated by Skyhook Scoped Plan Generator.*\n`;

    fs.writeFileSync(planPath, content, 'utf-8');

    return {
      path: planPath,
      content,
      req,
      requirement: req
    };
  }

  /**
   * Generate an individual delivery plan for a single epic
   * @param {string} epicId - Epic ID
   * @param {Object} ctx - SkyhookContext
   * @returns {Object} { path, content, epic }
   */
  static generateEpicPlan(epicId, ctx) {
    const skyhookDir = ctx.skyhookDir;
    const backlog = ctx.readBacklog();
    const epics = backlog.epics || [];
    const stories = backlog.stories || [];

    const epic = epics.find(e => e.id === epicId || e.id?.toLowerCase() === epicId?.toLowerCase());
    if (!epic) {
      throw new Error(`Epic not found: ${epicId}`);
    }

    const epicDir = path.join(skyhookDir, 'plan', 'epics');
    if (!fs.existsSync(epicDir)) {
      fs.mkdirSync(epicDir, { recursive: true });
    }

    const planPath = path.join(epicDir, `${epic.id}.md`);
    const childStories = stories.filter(s => s.epicId === epic.id || (Array.isArray(epic.childStories) && epic.childStories.includes(s.id)));

    let content = `# Epic Plan: ${epic.id} — ${epic.title}\n\n`;
    content += `> **Status**: \`${epic.status || 'backlog'}\` | **Target Date**: \`${epic.targetDate || 'TBD'}\`\n`;
    content += `> **Generated**: ${getTimestamp()}\n\n`;
    content += `---\n\n`;

    content += `## 1. High-Level Outcome & Goal\n\n`;
    content += `${epic.goal || epic.description || 'No goal statement defined.'}\n\n`;

    if (epic.successMetrics && epic.successMetrics.length > 0) {
      content += `### Success Metrics (KPIs)\n`;
      content += epic.successMetrics.map(m => `- [ ] ${m}`).join('\n') + '\n\n';
    }

    content += `## 2. Child Stories & Work Breakdown\n\n`;
    if (childStories.length > 0) {
      content += `| Story ID | Title | Status | Priority | Estimate | Dependencies |\n`;
      content += `|:---------|:------|:-------|:---------|:---------|:-------------|\n`;
      for (const s of childStories) {
        const deps = (s.dependsOn || []).join(', ') || 'None';
        const points = s.storyPoints ? `${s.storyPoints} pts` : '—';
        content += `| **${s.id}** | ${s.title} | \`${s.status}\` | ${s.priority || 'medium'} | ${points} | ${deps} |\n`;
      }
      content += '\n';
    } else {
      content += `*No child stories registered under this epic.*\n\n`;
    }

    content += `## 3. Dependency Structure (Mermaid DAG)\n\n`;
    if (childStories.length > 0) {
      content += `\`\`\`mermaid\nflowchart TD\n`;
      for (const s of childStories) {
        const cleanTitle = s.title.replace(/[:;#`"<>{}|[\]]/g, ' ');
        content += `    ${s.id}["${cleanTitle} (${s.status})"]\n`;
        for (const depId of s.dependsOn || []) {
          content += `    ${depId} --> ${s.id}\n`;
        }
      }
      content += `\`\`\`\n\n`;
    }

    content += `## 4. Execution Guidance for AI Agents & Engineers\n\n`;
    content += `1. **Task Checkout**: Request ready tasks via \`skyhook get-next-task --agent <your-id> --lease 30\`.\n`;
    content += `2. **State Progression**: Advance status via \`skyhook update-status --storyId <ID> --status <status>\`.\n`;
    content += `3. **Completion**: When all child stories are marked \`done\`, Epic \`${epic.id}\` will automatically transition to \`done\`.\n\n`;
    content += `---\n*Generated by Skyhook Scoped Plan Generator.*\n`;

    fs.writeFileSync(planPath, content, 'utf-8');

    return {
      path: planPath,
      content,
      epic
    };
  }

  /**
   * Generate plans for all requirements and epics
   * @param {Object} ctx - SkyhookContext
   * @param {Array<Object>} symbols - Codebase symbols
   * @returns {Object} Summary of generated plans
   */
  static generateAllScopedPlans(ctx, symbols = []) {
    const funcReqs = ctx.readFunctionalReqs()?.requirements || [];
    const nonFuncReqs = ctx.readNonFunctionalReqs()?.requirements || [];
    const allReqs = [...funcReqs, ...nonFuncReqs];
    const epics = ctx.readBacklog()?.epics || [];

    const reqResults = [];
    for (const req of allReqs) {
      try {
        reqResults.push(this.generateRequirementPlan(req.id, ctx, symbols));
      } catch {
        // Skip on error
      }
    }

    const epicResults = [];
    for (const epic of epics) {
      try {
        epicResults.push(this.generateEpicPlan(epic.id, ctx));
      } catch {
        // Skip on error
      }
    }

    return {
      requirementsCount: reqResults.length,
      epicsCount: epicResults.length,
      requirementPlans: reqResults.map(r => r.path),
      epicPlans: epicResults.map(e => e.path)
    };
  }
}
