/**
 * Skyhook Auto-ADR Generation - Creates complete ADRs from decision data
 */

const fs = require('fs');
const path = require('path');
const { parseYaml } = require('./simple-yaml.js');

// ==================== AUTO-ADR GENERATOR ====================

/**
 * Generate a complete ADR from decision data and project context
 * @param {Object} decisionData - Decision data from user
 * @param {Object} context - Project context for auto-filling
 * @returns {string} Complete ADR markdown
 */
function generateADR(decisionData, context) {
  const id = decisionData.id || generateULID();
  const timestamp = getTimestamp();
  
  // Get alternatives from profile/context
  const alternatives = generateAlternatives(decisionData, context);
  
  // Generate consequences analysis
  const consequences = generateConsequences(decisionData, context);
  
  // Find related requirements
  const relatedReqs = findRelatedRequirements(decisionData, context);
  
  // Find related decisions
  const relatedDecisions = findRelatedDecisions(decisionData, context);
  
  const adr = `# Decision: ${decisionData.title}

**ID**: ${id}
**Status**: ${decisionData.status || 'proposed'}
**Category**: ${decisionData.category || 'architecture'}
**Date**: ${timestamp}
**Author**: ${decisionData.author || 'AI Agent + Human'}

## Context

${decisionData.context || 'No context provided.'}

${generateContextDetails(context, decisionData)}

## Decision

${decisionData.decision || 'No decision stated.'}

${generateDecisionRationale(decisionData, context)}

## Consequences

### Positive
${consequences.positive.map(c => `- ${c}`).join('\n') || '- (None documented)'}

### Negative
${consequences.negative.map(c => `- ${c}`).join('\n') || '- (None documented)'}

### Neutral / Risks
${consequences.neutral.map(c => `- ${c}`).join('\n') || '- (None documented)'}

## Alternatives Considered

| Alternative | Description | Pros | Cons |
|-------------|-------------|------|------|
${alternatives.map(a => `| ${a.name} | ${a.description} | ${a.pros.join('; ')} | ${a.cons.join('; ')} |`).join('\n') || '| No alternatives documented | | | |'}

## Related Requirements

${relatedReqs.length > 0 
  ? relatedReqs.map(r => `- **${r.id}**: ${r.title} (${r.status})`).join('\n')
  : 'No directly related requirements documented.'}

## Related Decisions

${relatedDecisions.length > 0
  ? relatedDecisions.map(d => `- **${d.id}**: ${d.title} (${d.status})`).join('\n')
  : 'No related decisions documented.'}

## Implementation Notes

${generateImplementationNotes(decisionData, context)}

## Validation Criteria

${generateValidationCriteria(decisionData, context)}

---

*Generated by Skyhook Auto-ADR on ${timestamp}*
*Review and update before marking as "accepted"*
`;

  return adr;
}

/**
 * Generate alternatives from profile defaults and context
 */
function generateAlternatives(decisionData, context) {
  const alternatives = [];
  
  // Add user-provided alternatives
  if (decisionData.alternatives && Array.isArray(decisionData.alternatives)) {
    for (const alt of decisionData.alternatives) {
      alternatives.push({
        name: alt.name || alt.title || 'Alternative',
        description: alt.description || alt.reason || 'No description',
        pros: alt.pros || ['(Add pros)'],
        cons: alt.cons || ['(Add cons)']
      });
    }
  }
  
  // Add profile-suggested alternatives based on decision category
  const profileAlts = getProfileAlternatives(decisionData.category, context, decisionData);
  for (const alt of profileAlts) {
    if (!alternatives.some(a => a.name.toLowerCase() === alt.name.toLowerCase())) {
      alternatives.push(alt);
    }
  }
  
  return alternatives;
}

/**
 * Get profile-suggested alternatives for decision category
 */
function getProfileAlternatives(category, context, decisionData) {
  const profile = context.profile || 'web-app';
  const alts = [];
  
  if (category === 'technology' || category === 'architecture') {
    // Database alternatives
    if (decisionMentions(decisionData, ['database', 'db', 'postgres', 'mysql', 'mongo'])) {
      alts.push(
        { name: 'PostgreSQL', description: 'Robust, ACID-compliant, great JSON support', pros: ['Mature', 'JSONB', 'Extensions'], cons: ['Operational overhead'] },
        { name: 'MySQL', description: 'Wide adoption, good performance', pros: ['Familiar', 'Good tooling'], cons: ['Weaker JSON'] },
        { name: 'SQLite', description: 'Embedded, zero-config', pros: ['Simple', 'Portable'], cons: ['No concurrency', 'No network'] },
        { name: 'MongoDB', description: 'Document database, flexible schema', pros: ['Flexible', 'Scales horizontally'], cons: ['No ACID (historically)', 'Memory'] }
      );
    }
    
    // Auth alternatives
    if (decisionMentions(decisionData, ['auth', 'authentication', 'login'])) {
      alts.push(
        { name: 'NextAuth.js', description: 'Full-featured auth for Next.js', pros: ['Built-in providers', 'Type-safe', 'Secure defaults'], cons: ['Next.js only', 'Learning curve'] },
        { name: 'Clerk', description: 'Managed auth service', pros: ['Drop-in', 'MFA built-in', 'Admin dashboard'], cons: ['Cost', 'Vendor lock-in'] },
        { name: 'Supabase Auth', description: 'Open-source auth with Postgres', pros: ['Integrated with DB', 'Open source'], cons: ['Self-host complexity'] },
        { name: 'Custom JWT', description: 'Roll your own with jsonwebtoken', pros: ['Full control', 'No deps'], cons: ['Security risk', 'Maintenance burden'] }
      );
    }
    
    // Deployment alternatives
    if (decisionMentions(decisionData, ['deploy', 'hosting', 'vercel', 'aws'])) {
      alts.push(
        { name: 'Vercel', description: 'Optimized for Next.js', pros: ['Zero config', 'Edge network', 'Preview deploys'], cons: ['Vendor lock-in', 'Cost at scale'] },
        { name: 'Netlify', description: 'Static + functions', pros: ['Generous free tier', 'Forms', 'Edge functions'], cons: ['Less Next.js optimization'] },
        { name: 'AWS (ECS/Lambda)', description: 'Full control on AWS', pros: ['Full control', 'Integrated services'], cons: ['Complexity', 'Ops burden'] },
        { name: 'Docker + VPS', description: 'Self-hosted containers', pros: ['Full control', 'Cost predictable'], cons: ['Ops burden', 'No preview deploys'] },
        { name: 'Fly.io / Railway / Render', description: 'Modern PaaS', pros: ['Simple', 'Global', 'Good DX'], cons: ['Newer', 'Less enterprise features'] }
      );
    }
  }
  
  return alts.slice(0, 5); // Limit to 5 alternatives
}

function decisionMentions(decisionData, keywords) {
  const text = `${decisionData.title} ${decisionData.decision} ${decisionData.context}`.toLowerCase();
  return keywords.some(k => text.includes(k.toLowerCase()));
}

/**
 * Generate consequences analysis
 */
function generateConsequences(decisionData, context) {
  const positive = [];
  const negative = [];
  const neutral = [];
  
  // Auto-generate based on category and context
  const category = decisionData.category || 'architecture';
  
  if (category === 'technology') {
    positive.push('Standardizes technology stack across team');
    positive.push('Enables consistent tooling and practices');
    negative.push('Team learning curve for new technology');
    negative.push('Migration cost if switching later');
    neutral.push('Vendor/tool lock-in risk');
    neutral.push('Community support and hiring pool considerations');
  }
  
  if (category === 'architecture') {
    positive.push('Improves system modularity and maintainability');
    positive.push('Enables independent scaling of components');
    negative.push('Increased operational complexity');
    negative.push('Network latency between services');
    neutral.push('Requires robust observability and monitoring');
    neutral.push('Distributed tracing and debugging complexity');
  }
  
  if (category === 'security') {
    positive.push('Reduces attack surface');
    positive.push('Compliance with security standards');
    negative.push('May impact user experience (MFA, session timeouts)');
    negative.push('Implementation and maintenance overhead');
    neutral.push('Regular security audits required');
    neutral.push('Key rotation and secret management complexity');
  }
  
  if (category === 'ux' || category === 'design') {
    positive.push('Improves user experience and accessibility');
    positive.push('Consistent design language across product');
    negative.push('Design system maintenance overhead');
    negative.push('May constrain creative flexibility');
    neutral.push('Component library versioning strategy needed');
  }
  
  // Add user-provided consequences
  if (decisionData.consequences) {
    if (decisionData.consequences.positive) positive.push(...decisionData.consequences.positive);
    if (decisionData.consequences.negative) negative.push(...decisionData.consequences.negative);
    if (decisionData.consequences.neutral) neutral.push(...decisionData.consequences.neutral);
  }
  
  return { positive, negative, neutral };
}

/**
 * Find related requirements
 */
function findRelatedRequirements(decisionData, context) {
  const related = [];
  
  if (decisionData.relatedRequirements && Array.isArray(decisionData.relatedRequirements)) {
    const skyhookDir = findSkyhookDir(context.projectDir || process.cwd());
    if (skyhookDir) {
      const functionalReqs = readYaml(path.join(skyhookDir, 'requirements', 'functional.yaml')) || { requirements: [] };
      const nonFunctionalReqs = readYaml(path.join(skyhookDir, 'requirements', 'non-functional.yaml')) || { requirements: [] };
      const allReqs = [...functionalReqs.requirements, ...nonFunctionalReqs.requirements];
      
      for (const reqId of decisionData.relatedRequirements) {
        const req = allReqs.find(r => r.id === reqId);
        if (req) {
          related.push({ id: req.id, title: req.title, status: req.status, category: req.category });
        }
      }
    }
  }
  
  return related;
}

/**
 * Find related decisions
 */
function findRelatedDecisions(decisionData, context) {
  const related = [];
  
  const skyhookDir = findSkyhookDir(context.projectDir || process.cwd());
  if (skyhookDir) {
    const decisions = readYaml(path.join(skyhookDir, 'decisions', 'index.yaml')) || { decisions: [] };
    
    // Find decisions in same category
    for (const d of decisions.decisions || []) {
      if (d.category === decisionData.category && d.id !== decisionData.id) {
        related.push({ id: d.id, title: d.title, status: d.status });
      }
    }
  }
  
  return related.slice(0, 5);
}

/**
 * Generate implementation notes
 */
function generateImplementationNotes(decisionData, context) {
  let notes = '';
  
  if (decisionData.implementationNotes) {
    notes += decisionData.implementationNotes + '\n\n';
  }
  
  notes += '### Suggested Implementation Steps\n\n';
  
  if (decisionData.category === 'technology') {
    notes += '1. Add dependency to package.json\n';
    notes += '2. Configure in application\n';
    notes += '3. Update CI/CD pipeline if needed\n';
    notes += '4. Document in team onboarding\n';
    notes += '5. Add to architecture decision log\n';
  } else if (decisionData.category === 'architecture') {
    notes += '1. Create module/service boundaries\n';
    notes += '2. Define interfaces/contracts\n';
    notes += '3. Implement communication layer\n';
    notes += '4. Add observability (logging, metrics, tracing)\n';
    notes += '5. Update deployment configuration\n';
  } else {
    notes += '1. Define acceptance criteria\n';
    notes += '2. Create implementation plan\n';
    notes += '3. Implement with tests\n';
    notes += '4. Code review and merge\n';
    notes += '5. Update documentation\n';
  }
  
  return notes;
}

/**
 * Generate validation criteria
 */
function generateValidationCriteria(decisionData, context) {
  let criteria = '';
  
  criteria += '- [ ] Decision reviewed by team\n';
  criteria += '- [ ] Alternatives documented and evaluated\n';
  criteria += '- [ ] Consequences understood and accepted\n';
  criteria += '- [ ] Related requirements linked\n';
  criteria += '- [ ] Implementation plan created\n';
  
  if (decisionData.category === 'technology') {
    criteria += '- [ ] Dependency added to package.json\n';
    criteria += '- [ ] TypeScript types available (if applicable)\n';
    criteria += '- [ ] CI/CD updated if needed\n';
    criteria += '- [ ] Security audit passed (if new dependency)\n';
  }
  
  if (decisionData.category === 'security') {
    criteria += '- [ ] Threat model updated\n';
    criteria += '- [ ] Penetration test scheduled (if major change)\n';
    criteria += '- [ ] Compliance requirements verified\n';
  }
  
  return criteria;
}

// ==================== HELPERS ====================

function generateULID() {
  const chars = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';
  let id = '';
  for (let i = 0; i < 26; i++) {
    id += chars[Math.floor(Math.random() * chars.length)];
  }
  return id;
}

function getTimestamp() {
  return new Date().toISOString();
}

function findSkyhookDir(projectDir) {
  let dir = projectDir;
  while (dir !== path.parse(dir).root) {
    if (fs.existsSync(path.join(dir, '.skyhook'))) {
      return path.join(dir, '.skyhook');
    }
    dir = path.dirname(dir);
  }
  return null;
}

function readYaml(filePath) {
  try {
    const content = fs.readFileSync(filePath, 'utf-8');
    const { parseYaml } = require('./simple-yaml.js');
    return parseYaml(content);
  } catch {
    return null;
  }
}

function generateContextDetails(context, decisionData) {
  let details = '';
  
  if (context.projectType) {
    details += `**Project Type**: ${context.projectType}\n\n`;
  }
  
  if (context.profile) {
    details += `**Profile**: ${context.profile}\n\n`;
  }
  
  if (context.techStack && context.techStack.technologies) {
    const relevantTech = context.techStack.technologies.filter(t => 
      decisionMentions(decisionData, [t.name, t.category])
    );
    if (relevantTech.length > 0) {
      details += `**Relevant Tech Stack**:\n`;
      for (const tech of relevantTech) {
        details += `- ${tech.category}: ${tech.name} ${tech.version || ''}\n`;
      }
      details += '\n';
    }
  }
  
  return details;
}

function generateDecisionRationale(decisionData, context) {
  let rationale = '';
  
  if (decisionData.rationale) {
    rationale += decisionData.rationale + '\n\n';
  }
  
  rationale += 'This decision was made based on:\n\n';
  rationale += '- Project requirements and constraints\n';
  rationale += '- Team expertise and preferences\n';
  rationale += '- Industry best practices\n';
  rationale += '- Long-term maintainability\n\n';
  
  return rationale;
}

function decisionMentions(decisionData, keywords) {
  const text = `${decisionData.title} ${decisionData.decision} ${decisionData.context}`.toLowerCase();
  return keywords.some(k => text.includes(k.toLowerCase()));
}

module.exports = { generateADR };
